### ISSUE TITLE
Problems with enums

### ISSUE THREAD

**Issue by yallie** [marek-stoj/ImmDoc.NET#5]
1. Enums are declared like "public sealed class Foo : Enum" instead of "public enum Foo":
   ![Screenshot](http://yallie.github.com/ImmDoc.NET/ImmDocNet_EnumDeclaration.png)
2. Enum members include "value__" field:
   ![Screenshot](http://yallie.github.com/ImmDoc.NET/ImmDocNet_EnumValue.png)

**Comment by yallie** [comment]
Looks like typeDefinition.IsClass returns true for enums.

**Comment by marek-stoj** [comment]
Thanks!
