### ISSUE TITLE
MSDN links don't work for generic types

### ISSUE THREAD

**Issue by yallie** [marek-stoj/ImmDoc.NET#8]
Looks like generic types don't have readable aliases in MSDN:
- System.Action -> http://msdn.microsoft.com/library/system.action.aspx
- System.Action&lt;T&gt; -> http://msdn.microsoft.com/library/018hxwa8.aspx
- System.Action&lt;T1, T2&gt; -> http://msdn.microsoft.com/library/bb549311.aspx
  ...

I tried the following URLs:
- http://msdn.microsoft.com/library/system.action`1.aspx
- http://msdn.microsoft.com/library/system.action{t}.aspx
- http://msdn.microsoft.com/library/system.action(t).aspx
- [http://msdn.microsoft.com/library/system.action&lt;t&gt;.aspx](http://msdn.microsoft.com/library/system.action<t>.aspx)

None of them worked.

I'm still trying to find a quick way to map class names to MSDN links.
The ultimate way of doing this is to use MTPS Content Service:
http://services.msdn.microsoft.com/ContentServices/ContentService.asmx
But I guess it would be much better to find an offline solution.

**Comment by marek-stoj** [comment]
Maybe in such cases we could link to Google/Bing/MSDN search? I was thinking about linking to Google's "I'm feeling lucky" to get the first search result but couldn't find the way to do it.

**Comment by yallie** [comment]
I wrote a simple console app which connects to MTPS service and spits out classes that don't have readable aliases. Seems like generic types are not the only ones that fall in this category.

The list won't be long, about 100k, I think. I'm going to gzip it and link to ImmDocLib as a resource.

**Comment by marek-stoj** [comment]
Sounds good.

**Comment by yallie** [comment]
It's also possible to download the whole list of BCL classes. We can use this list to check whether a type is a part of base class library. But this list is going to be huge... I'm not sure if the game worth the candle.

**Comment by marek-stoj** [comment]
I don't think it's worth it.

**Comment by yallie** [comment]
Out of curiosity, I run my program to pull the complete list of BCL classes for .NET Framework 4.5 (15461 classes). The dataset turned out to be surprisingly small, ~166 kilobytes in gzip format. With this dataset, we can create short MSDN links for all BCL types and sort out misspelled garbage.
